### ISSUE TITLE
Error `Unhandled: Stream connection ended and command aborted. It might have been processed`

### ISSUE THREAD

**Issue by djechelon** [gibinfrancis/RedisCacheExtension#6]
I am having troubles using the plugin in a hybrid architecture IaaS+PaaS.

Scenario: the release pipeline runs on Agent pool on an Ubuntu 20.04 IaaS machine where I installed the agent.
Redis is deployed in PaaS
Redis is connected to Private Link
I can ping/telnet Redis from bash
Redis configuration is protected by variable group
Pipeline is configured in WYSIWYG

YAML

```
#Your build pipeline references an undefined variable named ‘redis_host’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘redis_port’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘redis_password’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: gbnz.redis-cache-clear.redisCacheFlushAll-release-task.redisCacheFlushAll@1
  displayName: 'Redis Cache Flush all'
  inputs:
    redishost: '$(redis_host)'
    redisport: '$(redis_port)'
    rediskey: '$(redis_password)'
```

![Variables](https://user-images.githubusercontent.com/3042285/164199482-fc639a6c-0db8-42e7-81cb-503b97e6ff68.png)

The variables are defined correctly. The above setup **works** in a PaaS-vanilla environment (Redis is accessible publicly AND pipeline runs on Azure) in another pipeline.

The result is

```
2022-04-20T09:35:48.4537969Z ##[section]Starting: Redis Cache Flush all
2022-04-20T09:35:48.4545693Z ==============================================================================
2022-04-20T09:35:48.4546035Z Task         : Redis Cache Flush all
2022-04-20T09:35:48.4546302Z Description  : Runs Flush all command in the redis server
2022-04-20T09:35:48.4546526Z Version      : 1.1.0
2022-04-20T09:35:48.4546729Z Author       : Gibin Francis
2022-04-20T09:35:48.4546911Z Help         : 
2022-04-20T09:35:48.4547151Z ==============================================================================
2022-04-20T09:35:48.8581040Z Cache flushed successfully
2022-04-20T09:35:48.8945325Z ##[error]Unhandled: Stream connection ended and command aborted. It might have been processed.
2022-04-20T09:35:48.9020725Z ##[section]Finishing: Redis Cache Flush all
```

Should you need additional clarification, please ask here

**Comment by djechelon** [comment]
To add a little more information

If I run the following from the command line

`redis-cli -a [KEY] -h [HOST] -p [PORT] flushall` hangs if PORT equals 6380 and works if PORT equals 6379. Both ports can be telnet-ed.

I have tried to switch the pipeline to port 6379 and the step running your plugin is hanging at the moment. I'll temporarily replace with the CLI I guess

**Comment by jasenf** [comment]
We get the same error on all commands, running this in an Azure Devops release:

Unhandled: Stream connection ended and command aborted. It might have been processed.

The command is not being executed.

**Comment by gibinfrancis** [comment]
Can you please mention the authentication type you are using

**Comment by jasenf** [comment]
Hi there, just using password authentication.

**Comment by gibinfrancis** [comment]
kindly check with the latest 2.0.0 version
